### ISSUE TITLE
Hi, I found cascade-rcnn mode seems don't support multi-gpu?

### ISSUE THREAD

**Issue by weitaoatvison** [guoruoqian/cascade-rcnn_Pytorch#1]
Hi, I found cascade-rcnn mode seems don't support multi-gpu? When I running with no cascace-rcnn mode , it can running on multi-gpu, however it crashed when I running with cascade-rcnn model. The Error is:
Traceback (most recent call last):
  File "trainval_net.py", line 364, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 74, in forward
    return self.gather(outputs, self.output_device)
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 86, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 65, in gather
    return gather_map(outputs)
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 60, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/wet/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 60, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

**Comment by weitaoatvison** [comment]
I have solved the problem. The error is caused by a return value in fpn_cascade. The type of the value is float, and can't be gather.

**Comment by guoruoqian** [comment]
Thanks a lot! Now, i fix the bug. Thanks!

**Comment by Allenwutao** [comment]
@weitaoatvison Could you give the example how to solve the problem?

**Comment by Allenwutao** [comment]
@weitaoatvison @guoruoqian Could you give the example how to solve the problem?

**Comment by guoruoqian** [comment]
i change [this code](https://github.com/guoruoqian/cascade-rcnn_Pytorch/blob/8b2fe322ad56f327cb6b66ea041e6e9a26c95fa0/lib/model/fpn/cascade/fpn.py#L443)  from 0 to cls_prob_3rd.
