### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by 17320266033** [guoruoqian/cascade-rcnn_Pytorch#43]
i use torch=0.3.1 torchvision=0.3.1 cuda=9.0  when I try to train this network, I got this error :
should i use torch=0.2.0?

Traceback (most recent call last):
  File "/home/tju/software/pycharm-2018.2.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/tju/software/pycharm-2018.2.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/tju/software/pycharm-2018.2.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/tju/zhangbing/tianchi/cascade-rcnn_Pytorch-master/trainval_net.py", line 26, in <module>
    from model.utils.net_utils import adjust_learning_rate, save_checkpoint
  File "/home/tju/zhangbing/tianchi/cascade-rcnn_Pytorch-master/lib/model/utils/net_utils.py", line 11, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/tju/zhangbing/tianchi/cascade-rcnn_Pytorch-master/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/tju/zhangbing/tianchi/cascade-rcnn_Pytorch-master/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/tju/.local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
We've got an error while stopping in post-mortem: <type 'exceptions.KeyboardInterrupt'>

**Comment by kingwpf** [comment]
same error, my pytorch version is 1.2.0

**Comment by luckyxianxian** [comment]
版本要求pytorch小于0.4.0

**Comment by zzu0654** [comment]
same error, my pytorch version is 1.1.0，can  you help me?

**Comment by zzu0654** [comment]
> 版本要求pytorch小于0.4.0
我的torchvision版本是0.3.0，torch版本是1.1.0，但是同样的错误，请问您清楚吗？
