### ISSUE TITLE
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor

### ISSUE THREAD

**Issue by huiyang865** [guoruoqian/cascade-rcnn_Pytorch#7]
Hi,
I try to run the trainval_net.py file to train model with VOC 2007 data. But an error appears as following:
Traceback (most recent call last):
  File "/home/robert/Documents/cascade-rcnn_Pytorch/trainval_net.py", line 379, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/robert/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/robert/Documents/cascade-rcnn_Pytorch/lib/model/fpn/cascade/fpn.py", line 193, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(rpn_feature_maps, im_info, gt_boxes, num_boxes)
  File "/home/robert/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/robert/Documents/cascade-rcnn_Pytorch/lib/model/rpn/rpn_fpn.py", line 109, in forward
    rpn_data = self.RPN_anchor_target((rpn_cls_score_alls.data, gt_boxes, im_info, num_boxes, rpn_shapes))
  File "/home/robert/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/robert/Documents/cascade-rcnn_Pytorch/lib/model/rpn/anchor_target_layer_fpn.py", line 141, in forward
    positive_weights = 1.0 / num_examples
  File "/home/robert/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 320, in __rdiv__
    return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa9a0a3cc50>> ignored

I have tried the pytorch of python2.7 and python3.6, all of them have the same error. Do you meet it?

**Comment by KevinQian97** [comment]
modify faster-rcnn.pytorch\lib\model\rpn\anchor_target_layer.py +156, from

num_examples = torch.sum(labels[i] >= 0)

to

num_examples = torch.sum(labels[i] >= 0).item()

and

labels = gt_boxes[:,:,4].contiguous().view(-1).index(offset.view(-1))\ .view(batch_size, -1)

to

labels = gt_boxes[:,:,4].contiguous().view(-1).index((offset.view(-1), ))\ .view(batch_size, -1)
